name: Release
on:
    push:
        tags:
            - v[0-9]+.*
    workflow_dispatch:

permissions:
    contents: write
    id-token: write
    actions: write

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v4

            # Release
            - name: Release
              uses: taiki-e/create-gh-release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            # Upload assets
            - name: Upload assets
              uses: taiki-e/upload-rust-binary-action@v1
              with:
                  bin: ssh-remote-exec
                  token: ${{ secrets.GITHUB_TOKEN }}
                  include: README.md
                  leading-dir: true
